[build-system]
requires = [
    "setuptools",
    "wheel",
    "Cython",
    "numpy",
    "scipy",
    "pandas",
    "scikit-learn",
    "statsmodels",
    "joblib"
]
build-backend = "setuptools.build_meta"
