# Render Blueprint for Flask + Python App
# Docs: https://render.com/docs/blueprint-spec

services:
  - type: web
    name: atos-flask-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python run.py
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: SECRET_KEY
        sync: false
    plan: free
